### ISSUE TITLE
nlds put Exception during callback: (psycopg2.errors.InvalidTextRepresentation) invalid input value for enum state: "CATALOG_ROLLBACK" LINE 1: UPDATE sub_record SET state='CATALOG_ROLLBACK', retry_count=...

### ISSUE THREAD

**Issue by mbanjestfc** [cedadev/nlds#81] opened 2024-01-08 10:07 UTC
I tried to put a file in CEDAPROC and gor the following error:
State of transaction for user:mbanjec, group:cedaproc, id:130
    id              : 130
    user            : mbanjec
    group           : cedaproc
    action          : put
    transaction id  : adbd7e39-c000-47be-a16f-ffb835cb5348
    label           :
    creation time   : 2023-12-22 09:41:26.644178
    state           : FAILED
    warnings        :
    sub records     ->
    +    id           : 54
         sub_id       : 96db9b63-02e8-49eb-954c-fdbd90d3bb85
         state        : FAILED
         retries      : 6
         last update  : 2024-01-02 10:43:37.365456
         failed files ->
         +    filepath : /gws/nopw/j04/cedaproc/title.crew.tsv
              reason   : Exception during callback: (psycopg2.errors.InvalidTextRepresentation) invalid input value for enum state: "CATALOG_ROLLBACK"
LINE 1: UPDATE sub_record SET state='CATALOG_ROLLBACK', retry_count=...
                                    ^

[SQL: UPDATE sub_record SET state=%(state)s, retry_count=(sub_record.retry_count + %(retry_count_1)s), last_updated=now() WHERE sub_record.id = %(sub_record_id)s]
[parameters: {'state': 'CATALOG_ROLLBACK', 'retry_count_1': 1, 'sub_record_id': 54}]
(Background on this error at: https://sqlalche.me/e/14/9h9h)
         +    filepath : /gws/nopw/j04/cedaproc/title.crew.tsv
              reason   : Exception during callback: S3 operation failed; code: AccessDenied, message: Access Denied, resource: /nlds.adbd7e39-c000-47be-a16f-ffb835cb5348, request_id: 05A4892AD29DD689, host_id: None

**Comment by jackleland** [comment] 2024-01-10 09:53
There's two issues here, one caused by not catching the S3 authentication failure, and one by improper migration of the STATE enum in postgres

**Comment by jackleland** [comment] 2024-01-10 16:37
This is now fixed as of [5eea605](https://github.com/cedadev/nlds/commit/5eea605c9aba3a2e5be2f0f9ff6a07e6150049b5) and a re-running of the migration of ENUMs. The authentication exception was being caught and handled appropriately

**Closed by jackleland** 2024-01-10 16:37 UTC
